### PR TITLE
Open file in denite insert/normal mode (New Tab, Vertical and Horizontal Split)

### PR DESCRIPTION
**Pull request by jhkersul**
Adding possibility to open file faster using Denite.

When still in insert mode, press:
* CTRL + T -> Open file in a new tab
* CTRL + V -> Open file vertically
* CTRL + H -> Open file horizontally 

Added this commands in the command list :)

### CODE REVIEW

**Comment by ctaylo21** [comment]
I like the idea, but I feel like I might need a more scalable way to handle mappings. For example, I don't use tabs, so that mapping wouldn't be useful for me. Having said that, I would like a way to allow people to define custom mappings while keeping up to date with the repo without forking (if they wanted).

As a side note, I will probably use the vertical split mapping, as that is the one I would use. I will likely tweak it to be:

`call denite#custom#map('insert,normal', "<C-v>", '<denite:do_action:vsplit>')`

as I will occasionally browse file lists in "normal" mode and I still would like that mapping to work.

**Comment by jhkersul** [comment]
About splitting shortcut on normal mode, totally agree! 

But I'm really interested in something: You don't use tabs? 🤔😱

**Comment by ctaylo21** [comment]
Nope! I use the `;` mapping to fuzzy find any open file or just browse through them manually, so I don't have any need for tabs. I might potentially merge this in, though. As it's a Denite mapping only, and I do think it's useful. I think I'd just add the addition of the `normal` mode mapping and it looks good!

**Comment by jhkersul** [comment]
Sorry for taking this long, but I've made the changes to work in insert/normal mode :)

**Comment by ctaylo21** [comment]
Awesome, thank you!

**Comment by gfsd3v** [comment]
Sorry for bringing this up again, but I'm having a little trouble trying to make this work, when I do CTRL + T from the denite fzf (LEADER + T) I get a "E73: tag stack empty", any ideas on how to fix it ?

**Comment by ctaylo21** [comment]
@gfsd3v I think it's a bug after I upgraded Denite to the new version. Can you open a new issue?

**Comment by gfsd3v** [comment]
@ctaylo21 I don't know if I'm the best suit for that considering that I changed alot the original config.

**Comment by ctaylo21** [comment]
@gfsd3v No worries, I can make a bug. I do think it's valid and not related to your custom changes. I don't use those mappings, so I didn't validate them when I had to change how mappings work in the Denite upgrade.

**Pull request merged**
